###
# Copyright (c) 2015, Upnext Technologies Sp. z o.o.
# All rights reserved.
#
# This source code is licensed under the BSD 3-Clause License found in the
# LICENSE.txt file in the root directory of this source tree. 
###

colors:
  - "05796F"
  - "19A69A"
  - "63BC66"
  - "9BCD5F"
  - "FFA800"
  - "FFCB00"
  - "FFF048"
  - "D4E34A"
  - "FF6F3A"
  - "F2514B"
  - "EF3C79"
  - "AC41BE"
  - "7E53C5"
  - "5B69C3"
  - "3B4BB2"
  - "222C6F"
